### ISSUE TITLE
Add library bot was built on

### ISSUE THREAD

**Issue by NoPlaceLikeLocalhost** [Terminal/discordapps.dev#59]
I realized after logging into ls and also listing my bot there wasnt really a lib option or something on your bot i thought this would be nice to add since its easy.

![Lib thing](https://user-images.githubusercontent.com/38942626/49734983-95286780-fc4b-11e8-9d6a-a036bd8b676a.png)

**Comment by lepon01** [comment]
This is currently not a feature because an end user to the website would not need to know such information. I could implement this feature, but I would ideally put this information down here

![image](https://user-images.githubusercontent.com/13886925/49735885-6ed0ef00-fc80-11e8-9d7a-01848cd0b628.png)

**Comment by lepon01** [comment]
I've returned to this issue with more ideas
Namely,

- adding a box to select lib
- adding a box to select if it was built on top of existing technologies

**Comment by Andre601** [comment]
> I've returned to this issue with more ideas
> Namely,
>
> * adding a box to select lib
> * adding a box to select if it was built on top of existing technologies

What do you mean with "[...] on top of existing technologies"?
Like do you have some examples?

**Comment by lepon01** [comment]
Heavily modified red bot

**Comment by Andre601** [comment]
Such things shouldn't be allowed in the first place tbh, since they are technicly still a copy of an already existing bot....
But I'm not the guy that can judge here so.... 🤷‍♂️

**Comment by lepon01** [comment]
Well you should be allowed to judge
This is a community project after all

**Comment by IamTails** [comment]
Heavily modified Neko bot should be an option uwu

**Comment by 7coil** [comment]
![image](https://user-images.githubusercontent.com/13886925/56243283-2001ee80-6092-11e9-802c-c998c2a12c28.png)
what a great vote

**Comment by 7coil** [comment]
I have reconsidered the proposal and it is not suitable for the application store.
