### ISSUE TITLE
Languages should be sort in alphabetical order

### ISSUE THREAD

**Issue by dying** [Terminal/discordapps.dev#71]
As the title says, it will be nice to have the list of languages in alphabetical order, to make it easier to search.

**Comment by lepon01** [comment]
I've put my brain to this now, and am drafting some ideas on how to make this work

The easiest method of doing this would be using clientside JavaScript, as the server would have i18n outside of the template to process the order of the internationalised languages. Will look at soon

**Comment by 7coil** [comment]
This has been pushed to `ls13`
Wow it's been nearly 4 months.

```js
this.state.unusedLanguages
  .map(language => {
    return {
      language,
      message: intl.formatMessage({
        id: `locales.${language}`
      })
    }
  })
  .sort((a, b) => a.message.localeCompare(b.message))
  .map(({language, message}) => {
    return (
      <option value={language}>{message || ''}</option>
    )
  })
```
